modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="MIT"
[[mods]] #mandatory
modId="cpaper" #mandatory
version="0.1" #mandatory
displayName="Create: Paper" #mandatory
authors="Chemiofitor"
description='''
Create Style Papermaking.
'''
[[dependencies.cpaper]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.cpaper]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.cpaper]]
modId="create"
mandatory=true
versionRange="[6.0.6,)"
ordering="AFTER"
side="BOTH"
[[dependencies.cpaper]]
modId="farmersdelight"
mandatory=true
versionRange="[1.20.1-1.2.10,)"
ordering="NONE"
side="BOTH"